Us 0.10 fix few things
WildCodeSchool/2022-03-php-remotefr-p2-meme-flix pull request #17
Opened 2022-05-07 09:27 UTC by Samsuffy0100110

- Add user_id in MemeManager and MemeController, now one user_id per meme.id (feature ok)
- clean files and refactors 
- Add assets on vote.html.twig (thumb up and thumb down)
- Delete SelectOneById in VoteController and add in MemeController (not an array anymore)(feature ok)
- clean databases for deployment
- delete deads routes

2022-05-07 09:59 UTC, J007B approved these changes

2022-05-07 10:01 UTC, J007B approved these changes

2022-05-07 11:58 UTC, J007B approved these changes

2022-05-07 18:19 UTC, jfm-wcs requested changes

2022-05-07 18:19 UTC, jfm-wcs commented on src/Controller/MemeController.php
> +        $legend = $legendManager->selectOneById($id);
on est d'accord, ici il faudrait appeler ta super méthode du LegendManager `selectOneByIdAndVotes()` (qui devrait s'appeler `selectAllAndVotesByMemeId` d'ailleurs 😛) ?

2022-05-07 18:20 UTC, jfm-wcs commented
J'ai juste mis une question avant de pouvoir valider. 
Sinon le reste est testé et ça m'a l'air nickel 👍

2022-05-07 18:21 UTC, jfm-wcs commented on src/Controller/MemeController.php
> +        $legend = $legendManager->selectOneById($id);
avec un `$legends` (au pluriel) ;) (idem dans le twig et c'est good.

2022-05-07 18:24 UTC, jfm-wcs commented on src/Controller/MemeController.php
> +        $legend = $legendManager->selectOneById($id);
et après réflexion, une petite modif sur la méthode :
```php
public function selectOneByIdAndVotes(int $memeId)
    {
        $query = "SELECT *, COUNT(vote.legend_id) AS numVote FROM " . self::TABLE .
        " JOIN " . VoteManager::TABLE . " ON vote.legend_id=legend.id JOIN " .
        MemeManager::TABLE . " ON legend.meme_id=meme.id
        WHERE meme.id=:meme_id GROUP BY vote.legend_id";
//add bindValue() sur meme_id
        return $this->pdo->query($query)->fetchAll();
    }
```

2022-05-07 18:25 UTC, jfm-wcs commented on src/Controller/MemeController.php
> +        $legend = $legendManager->selectOneById($id);
la victoire est proche !!! 🕺 😉

2022-05-10 05:58 UTC, jfm-wcs approved these changes
Eh ben c'est gagné !

2022-05-10 05:59 UTC, merged