start make create meme page
WildCodeSchool/2022-03-php-remotefr-p2-meme-flix pull request #2
Opened 2022-04-19 06:31 UTC by Samsuffy0100110

J'ai commencé la page créer ton MEME, elle est en s2 mais j'ai pensé qu'elle avait sa place en s1

2022-04-20 07:08 UTC, AlexandreGuyonnetWCS approved these changes

2022-04-20 08:06 UTC, jfm-wcs requested changes

2022-04-20 08:06 UTC, jeanfrancois-morin commented on src/View/Meme/create.html.twig
> +                                    </button>
pour info, a dans un button ne peut pas marcher

2022-04-20 08:06 UTC, jfm-wcs commented on src/View/Meme/vote.html.twig
> +                                Quand tu comprend que tu va utiliser le MVC pour ton projet 2
ce fichier ne devrait pas être sur cette us isn't it ?

2022-04-20 08:58 UTC, J007B approved these changes

2022-04-21 14:13 UTC, jfm-wcs requested changes

2022-04-21 14:13 UTC, jfm-wcs commented on src/View/Meme/create.html.twig
> +                                <input value="Valider" type="button" style="width: 10rem" class="btn btn-outline-danger bg-white btn-lg text-center"></input>
ajouter attribut `form="form-id"`

2022-04-21 14:13 UTC, jeanfrancois-morin commented on src/View/Meme/create.html.twig
> +                            <form method="post" enctype="multipart/form-data">
ajouter `id="form-id"`

2022-04-22 07:54 UTC, merged