Admin Board create
WildCodeSchool/2022-03-php-remotefr-p2-meme-flix pull request #3
Opened 2022-04-20 07:00 UTC by Samsuffy0100110

2022-04-20 07:08 UTC, AlexandreGuyonnetWCS approved these changes

2022-04-20 08:15 UTC, jfm-wcs requested changes

2022-04-20 08:15 UTC, jfm-wcs commented on src/View/Private/admin.html.twig
> +                                <button type="button" class="btn btn-danger">Danger</button>
button dans a not possible

2022-04-20 08:56 UTC, J007B approved these changes

2022-04-21 14:21 UTC, jfm-wcs requested changes

2022-04-21 14:21 UTC, jfm-wcs commented on src/View/Private/admin.html.twig
> +                        <img id="image" src="http://lusile17.l.u.pic.centerblog.net/o/ca4f5ca4.jpg" class="img-fluid" alt="your image"></div>
ajouter class `w-100` sur img

2022-04-22 07:43 UTC, jfm-wcs approved these changes

2022-04-22 07:43 UTC, merged